# Generated by Django 5.2.8 on 2026-03-20 13:12

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# conversion.migrations.0003_backfill_admin_user_and_make_required

class Migration(migrations.Migration):

    replaces = [('conversion', '0001_initial'), ('conversion', '0002_conversiontask_user_fileupload_user_and_more'), ('conversion', '0003_backfill_admin_user_and_make_required')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'model_fileupload',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiers', models.TextField()),
            ],
            options={
                'db_table': 'model_gene',
            },
        ),
        migrations.CreateModel(
            name='FileGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.CharField(max_length=255)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('stop', models.IntegerField(blank=True, null=True)),
                ('nt', models.TextField(blank=True, null=True)),
                ('aa', models.TextField(blank=True, null=True)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversion.fileupload')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversion.gene')),
            ],
            options={
                'db_table': 'model_filegene',
            },
        ),
        migrations.AddField(
            model_name='fileupload',
            name='genes',
            field=models.ManyToManyField(blank=True, related_name='files', through='conversion.FileGene', to='conversion.gene'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConversionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_job_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_path', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('annotation', 'Annotation'), ('sequencing_ont', 'ONT Sequencing'), ('sequencing_illumina', 'Illumina Sequencing'), ('sequencing_ont_annotated', 'ONT Sequencing with Annotation'), ('sequencing_illumina_annotated', 'Illumina Sequencing with Annotation')], max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'converter_conversiontask',
            },
        ),
        migrations.RunPython(
            code=conversion.migrations.0003_backfill_admin_user_and_make_required.assign_admin_to_orphan_rows,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='conversiontask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
