# Generated by Django 5.2.8 on 2026-09-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_job_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('annotation', 'Annotation'), ('from_json', 'JSON Processing'), ('assembly_ont', 'ONT Assembly'), ('assembly_illumina', 'Illumina Assembly'), ('assembly_ont_annotated', 'ONT Assembly with Annotation'), ('assembly_illumina_annotated', 'Illumina Assembly with Annotation')], max_length=50)),
                ('input_files', models.ManyToManyField(blank=True, related_name='input_conversion_tasks', to='core.file')),
                ('output_files', models.ManyToManyField(blank=True, related_name='output_conversion_tasks', to='core.file')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_tasks', to='core.processgroup')),
            ],
            options={
                'db_table': 'converter_conversiontask',
            },
        ),
    ]
