# Generated by Django 5.2.8 on 2026-03-16 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_job_id', models.CharField(max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_path', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('annotation', 'Annotation'), ('sequencing_ont', 'ONT Sequencing'), ('sequencing_illumina', 'Illumina Sequencing'), ('sequencing_ont_annotated', 'ONT Sequencing with Annotation'), ('sequencing_illumina_annotated', 'Illumina Sequencing with Annotation')], max_length=50)),
            ],
            options={
                'db_table': 'converter_conversiontask',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'model_fileupload',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiers', models.TextField()),
            ],
            options={
                'db_table': 'model_gene',
            },
        ),
        migrations.CreateModel(
            name='FileGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.CharField(max_length=255)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('stop', models.IntegerField(blank=True, null=True)),
                ('nt', models.TextField(blank=True, null=True)),
                ('aa', models.TextField(blank=True, null=True)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversion.fileupload')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversion.gene')),
            ],
            options={
                'db_table': 'model_filegene',
            },
        ),
        migrations.AddField(
            model_name='fileupload',
            name='genes',
            field=models.ManyToManyField(blank=True, related_name='files', through='conversion.FileGene', to='conversion.gene'),
        ),
    ]
