# Generated by Django 5.2.8 on 2026-04-10 18:58

import os

import django.db.migrations.operations.special
from django.db import migrations, models


def _derive_process_name(task):
    if task.process_name:
        return task.process_name
    if task.previous_task_id and task.previous_task and task.previous_task.process_name:
        return task.previous_task.process_name
    source = (task.input_path or '').split(',')[0].strip()
    if source:
        return os.path.basename(source)
    return f"Process {task.id}"


def backfill_process_names(apps, schema_editor):
    ConversionTask = apps.get_model('conversion', 'ConversionTask')
    tasks = ConversionTask.objects.select_related('previous_task').order_by('id')
    for task in tasks:
        new_name = _derive_process_name(task)
        if task.process_name != new_name:
            task.process_name = new_name
            task.save(update_fields=['process_name'])


def rename_json_ingestion_to_from_json(apps, schema_editor):
    ConversionTask = apps.get_model('conversion', 'ConversionTask')
    ConversionTask.objects.filter(task_type='json_ingestion').update(task_type='from_json')

class Migration(migrations.Migration):

    replaces = [('conversion', '0003_conversiontask_process_name_and_json_type'), ('conversion', '0004_conversiontask_from_json_value')]

    dependencies = [
        ('conversion', '0002_conversiontask_previous_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversiontask',
            name='process_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversiontask',
            name='task_type',
            field=models.CharField(choices=[('annotation', 'Annotation'), ('from_json', 'From JSON'), ('sequencing_ont', 'ONT Sequencing'), ('sequencing_illumina', 'Illumina Sequencing'), ('sequencing_ont_annotated', 'ONT Sequencing with Annotation'), ('sequencing_illumina_annotated', 'Illumina Sequencing with Annotation')], max_length=50),
        ),
        migrations.RunPython(
            code=backfill_process_names,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=rename_json_ingestion_to_from_json,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
