# Generated by Django 5.2.8 on 2026-03-23 00:00

import conversion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_conversiontask_user_fileupload_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=conversion.models.file_upload_path),
        ),
    ]
