# Generated by Django 5.2.8 on 2026-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0003_conversiontask_process_name_and_json_type_squashed_0004_conversiontask_from_json_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversiontask',
            name='task_type',
            field=models.CharField(choices=[('annotation', 'Annotation'), ('from_json', 'From JSON'), ('assembly_ont', 'ONT Assembly'), ('assembly_illumina', 'Illumina Assembly'), ('assembly_ont_annotated', 'ONT Assembly with Annotation'), ('assembly_illumina_annotated', 'Illumina Assembly with Annotation')], max_length=50),
        ),
    ]
