# Generated by Django 5.2.8 on 2026-04-02 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _get_or_create_fallback_user(apps):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)

    existing = User._default_manager.order_by('pk').first()
    if existing is not None:
        return existing

    field_names = {field.name for field in User._meta.concrete_fields}
    username_field = getattr(User, 'USERNAME_FIELD', 'username')

    create_kwargs = {}
    if username_field in field_names:
        create_kwargs[username_field] = 'system_migration_user'
    if 'email' in field_names:
        create_kwargs['email'] = 'system-migration@local.invalid'
    if 'password' in field_names:
        create_kwargs['password'] = '!'
    if 'is_active' in field_names:
        create_kwargs['is_active'] = False
    if 'is_staff' in field_names:
        create_kwargs['is_staff'] = False
    if 'is_superuser' in field_names:
        create_kwargs['is_superuser'] = False

    return User._default_manager.create(**create_kwargs)


def backfill_null_user(apps, schema_editor):
    fallback_user = _get_or_create_fallback_user(apps)
    ConversionTask = apps.get_model('conversion', 'ConversionTask')
    FileUpload = apps.get_model('conversion', 'FileUpload')

    ConversionTask.objects.filter(user__isnull=True).update(user=fallback_user)
    FileUpload.objects.filter(user__isnull=True).update(user=fallback_user)


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0004_tasknotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_null_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='conversiontask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='TaskNotification'),
            ],
        ),
    ]
