# Generated by Django 5.2.8 on 2026-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0005_alter_conversiontask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversiontask',
            name='output_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
