# Generated by Django 5.2.8 on 2026-09-11 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0009_conversiontask_input_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversiontask',
            name='input_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_conversion_tasks', to='conversion.file'),
        ),
        migrations.RemoveField(
            model_name='conversiontask',
            name='input_path',
        ),
        migrations.RenameField(
            model_name='filegene',
            old_name='file_upload',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='conversiontask',
            name='output_path',
        ),
        migrations.AddField(
            model_name='conversiontask',
            name='output_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_conversion_tasks', to='conversion.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
    ]
