# Generated by Django 5.2.8 on 2026-09-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0010_rename_file_upload_filegene_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversiontask',
            name='input_file',
        ),
        migrations.AddField(
            model_name='conversiontask',
            name='input_file',
            field=models.ManyToManyField(blank=True, related_name='input_conversion_tasks', to='conversion.file'),
        ),
    ]
