# Generated by Django 5.2.8 on 2026-09-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0011_remove_conversiontask_input_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversiontask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
