# Generated by Django 5.2.8 on 2026-09-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0012_alter_conversiontask_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversiontask',
            old_name='input_file',
            new_name='input_files',
        ),
    ]
