# Generated by Django 5.2.8 on 2026-09-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0013_rename_input_file_conversiontask_input_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversiontask',
            name='output_file',
        ),
        migrations.AddField(
            model_name='conversiontask',
            name='output_files',
            field=models.ManyToManyField(blank=True, related_name='output_conversion_tasks', to='conversion.file'),
        ),
    ]
