# Generated by Django 5.2.8 on 2026-09-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0015_processgroup_conversiontask_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversiontask',
            name='process_name',
        ),
    ]
