# Generated by Django 5.2.8 on 2026-09-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0017_processgroup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversiontask',
            name='user',
        ),
    ]
