# Generated by Django 5.2.8 on 2026-09-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0018_remove_conversiontask_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversiontask',
            name='previous_task',
        ),
    ]
