# Generated by Django 5.2.8 on 2026-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0019_remove_conversiontask_previous_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversiontask',
            name='task_type',
            field=models.CharField(choices=[('annotation', 'Annotation'), ('from_json', 'JSON Processing'), ('assembly_ont', 'ONT Assembly'), ('assembly_illumina', 'Illumina Assembly'), ('assembly_ont_annotated', 'ONT Assembly with Annotation'), ('assembly_illumina_annotated', 'Illumina Assembly with Annotation'), ('prediction', 'Prediction')], max_length=50),
        ),
    ]
