# Generated by Django 5.2.8 on 2026-02-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationtask',
            name='output_path',
        ),
        migrations.AlterField(
            model_name='annotationtask',
            name='external_job_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
