# Generated by Django 5.2.8 on 2026-02-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_remove_annotationtask_output_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_job_id', models.CharField(max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_path', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('annotation', 'Annotation'), ('sequencing_ont', 'ONT Sequencing'), ('sequencing_illumina', 'Illumina Sequencing')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='AnnotationTask',
        ),
    ]
