# Generated by Django 5.2.8 on 2026-04-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_move_tables_to_notifications_namespace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='tasknotification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usernotificationsettings',
            table=None,
        ),
    ]
