# Para desarrollo

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../app:/app
    # Ejecutar con UID 1000 - No arrancar como root
    user: "1000:1000"
    ports:
      - "8080:8000"
    env_file:
      - ../.env
    depends_on:
      - redis
    networks:
      - bio-network


  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: sh -c "export PYTHONPATH=/app && celery -A app worker -l info"
    volumes:
      - ../app:/app
    # Ejecutar con UID 1000 - No arrancar como root
    user: "1000:1000"
    env_file:
      - ../.env
    depends_on:
      - redis
    networks:
      - bio-network

  redis:
    image: redis:7
    container_name: bio-web-redis
    volumes:
      - redis_data_web:/data
    networks:
      bio-network:
        aliases:
          - bio-web-redis

networks:
  bio-network:
    external: true
    name: bio-network

volumes:
  redis_data_web: