# Generated by Django 5.2.8 on 2026-09-28 12:53

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiers', models.TextField()),
            ],
            options={
                'db_table': 'model_gene',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=core.models.get_file_upload_path)),
                ('file_type', models.CharField(choices=[('fastq', 'FASTQ'), ('fasta', 'FASTA'), ('json', 'JSON'), ('csv', 'CSV')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_file',
            },
        ),
        migrations.CreateModel(
            name='FileGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.CharField(max_length=255)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('stop', models.IntegerField(blank=True, null=True)),
                ('nt', models.TextField(blank=True, null=True)),
                ('aa', models.TextField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.file')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gene')),
            ],
            options={
                'db_table': 'model_filegene',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='genes',
            field=models.ManyToManyField(blank=True, related_name='files', through='core.FileGene', to='core.gene'),
        ),
        migrations.CreateModel(
            name='ProcessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
