# Generated by Django 5.2.8 on 2025-12-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FileGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.CharField(max_length=255)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.fileupload')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.gene')),
            ],
        ),
        migrations.AddField(
            model_name='fileupload',
            name='genes',
            field=models.ManyToManyField(blank=True, related_name='files', through='model.FileGene', to='model.gene'),
        ),
    ]
