# Generated by Django 5.2.8 on 2026-02-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filegene',
            name='aa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filegene',
            name='nt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filegene',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filegene',
            name='stop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
